# Generated by Django 5.2.7 on 2025-10-26 13:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(max_length=30)),
                ('imagen', models.ImageField(upload_to='eventos/')),
                ('valor', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('asistentes', models.ManyToManyField(blank=True, related_name='eventos_inscritos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
